### ISSUE TITLE
Database migrations aren't run when using the trait

### ISSUE THREAD

**Issue by mstnorris** [laravel/browser-kit-testing#3]
Using the dev version of Laravel (namely the yet-to-be-released 5.4) I've done as the docs state, but the migrations are not being run.

I'm following along Adam Wathan's TDD course so using the previous `->visit` and `->see` methods.

**Comment by splatEric** [comment]
I am having the same problem ... am having a poke around to see if I can work out why ...

**Comment by splatEric** [comment]
Okay, looks like you need to switch the DatabaseMigrations use statement as well. Looking at the code in the ```Laravel\BrowserKitTesting\TestCase```, the [setupTraits](https://github.com/laravel/browser-kit-testing/blob/master/src/TestCase.php#L99-L118) is expecting Traits to be in the ```Laravel\BrowserKitTesting``` namespace, so this will apply for any ```Illuminate\Foundation\Testing\*``` traits you might be using.

In this particular case, instead of

```use Illuminate\Foundation\Testing\DatabaseMigrations;```

you need

```use Laravel\BrowserKitTesting\DatabaseMigrations;```

**Comment by splatEric** [comment]
The latest commit:

https://github.com/laravel/browser-kit-testing/commit/a0380837f7cf4520e22d0b0c00b868cf5988e231

has addressed this issue by using the core traits instead. So you can ignore my previous suggestion going forward!

**Comment by amochohan** [comment]
@taylorotwell looks like this issue can be closed
